apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  labels:
    "app.kubernetes.io/name": 'sonarqube'
    "app.kubernetes.io/instance": "sonarqube"
data:
  SONARQUBE_URL: {{ printf "http://%s" .Values.url }}
