commonLabels:
 app: "artifactory"
resources:
 - base.yaml
 - secret.yaml
patchesJson6902:
 - path: patch-statefulset.yaml
   target:
     group: apps
     version: v1
     kind: StatefulSet
     name: artifactory-artifactory
#
# - path: patch-test.yaml
#   target:
#     group: ""
#     version: v1
#     kind: Pod
#     name: jenkins-ui-test-f7vdc

