# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# nameOverride:
# fullnameOverride:

master:
  componentName: jenkins-master
  nodeSelector: {}
  tolerations: {}
  image: "jenkins/jenkins"
  imageTag: "lts"
  imagePullPolicy: "Always"
  useSecurity: true
  adminUser: admin
  # AdminPassword: <defaults to random>
  cpu: "200m"
  memory: "256Mi"
  serviceType: ClusterIP
  servicePort: 80
  targetPort: 8080
  serviceAnnotations: {}
  # Enable Kubernetes Liveness and Readiness Probes
  healthProbes: true
  healthProbesTimeout: 60
  slaveListenerPort: 50000
  # List of plugins to be install during Jenkins master start
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - workflow-job
    - credentials-binding
    - git
    - greenballs
    - blueocean
    - job-dsl
  # Used to approve a list of groovy functions in pipelines used the script-security plugin. Can be viewed under /scriptApproval
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  customConfigMap: false
  ingress:
    enabled: true

agent:
  enabled: true
  image: jenkins/jnlp-slave
  imageTag: latest
  component: "jenkins-slave"
  privileged: false
  cpu: "200m"
  memory: "256Mi"
  # You may want to change this to true while testing a new image
  alwaysPullImage: false
  # You can define the volumes that you want to mount for this container
  # Allowed types are: ConfigMap, EmptyDir, HostPath, Nfs, Pod, Secret
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
  nodeSelector: {}

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # ExistingClaim:
  ## jenkins data Persistent Volume Storage Class
  storageClass: "ibmc-file-gold"

  annotations: {}
  accessMode: ReadWriteOnce
  size: 20Gi
  volumes:
  #  - name: nothing
  #    emptyDir: {}
  mounts:
  #  - mountPath: /var/nothing
  #    name: nothing
  #    readOnly: true

networkPolicy:
  # Enable creation of NetworkPolicy resources.
  enabled: false
  # For Kubernetes v1.4, v1.5 and v1.6, use 'extensions/v1beta1'
  # For Kubernetes v1.7, use 'networking.k8s.io/v1'
  apiVersion: networking.k8s.io/v1


#master:
#  numExecutors: 5
#  ingress:
#    enabled: true
#
#persistence:
#  storageClass: "ibmc-file-gold"
