apiVersion: v1
kind: Secret
metadata:
  name: artifactory-access
  labels:
    "app.kubernetes.io/name": 'artifactory'
    "app.kubernetes.io/instance": "artifactory"
type: Opaque
stringData:
  ARTIFACTORY_PASSWORD: {{ .Values.password }}
  ARTIFACTORY_USER: {{ .Values.username }}
  ARTIFACTORY_ADMIN_ACCESS_USER: {{ .Values.adminAccessUser }}
  ARTIFACTORY_ADMIN_ACCESS_PASSWORD: {{ .Values.adminAccessPassword }}
